"""ADC v2 interoperability and guarded explicit upright capture, without COM I/O."""
import json
import math
import os
from pathlib import Path
import struct
import tempfile
import time
import unittest
from unittest.mock import patch

os.environ.setdefault('QT_QPA_PLATFORM', 'offscreen')
from PySide6.QtWidgets import QApplication

from host.app import Window
from host.core import Replay, SessionRecorder, StreamDecoder, crc16
from host.transport import SerialWorker
from test_host_ui import WorkerStub, FakePort


# Captured from tb_telemetry_v2's actual serialized UART output, independently
# supplied by the RTL bench rather than generated by the host fixture below.
RTL_GOLDEN = bytes.fromhex(
    'aa5502570000fd0209fd0c007afe6000e803030121950104785634120204fffffeff'
    '0902e8030a0213000b02db000c02ff020d02ff030e0200000f02ff031002e01f'
    '110238ff120120130400000200140498badcfeb735')
GOLDEN_VALUES = {
    'theta_q10': -759, 'omega_q10': 12, 'arm_q10': -390, 'arm_speed_q10': 96,
    'adc': 765, 'command_permille': 1000, 'fault': 0x21, 'first_fault': 0x20,
    'device_time_ms': 0x12345678, 'encoder_count': -65537, 'control_loop_us': 1000,
    'sensor_flags': 0x13, 'adc_down': 219, 'adc_up': 767, 'adc_raw': 1023,
    'adc_window_min': 0, 'adc_window_max': 1023, 'adc_mean_q4': 8160,
    'motor_command_permille': -200, 'firmware_version': 0x20000,
    'sample_counter': 0xfedcba98,
}


def tlv(kind, fmt, value):
    payload = struct.pack(fmt, value)
    return bytes((kind, len(payload))) + payload


def frame(sequence=1, version=2, theta=0, omega=0, state=0, fault=0,
          diagnostic=0x80, flags=12, firmware=0x20000, extra=b'', extensions=True):
    payload = struct.pack('<HHhhhhh', sequence, 767, theta, omega, 0, 0, 250)
    payload += bytes((state, 1, fault, diagnostic))
    if version == 2:
        if extensions:
            payload += tlv(1, '<I', 1000) + tlv(2, '<i', -50) + tlv(9, '<H', 1000)
            if flags is not None:
                payload += tlv(10, '<H', flags)
            payload += tlv(11, '<H', 219) + tlv(12, '<H', 767)
            payload += tlv(13, '<H', 766) + tlv(14, '<H', 763) + tlv(15, '<H', 770)
            payload += tlv(16, '<H', 12265) + tlv(17, '<h', -200) + tlv(18, '<B', 0)
            if firmware is not None:
                payload += tlv(19, '<I', firmware)
            payload += tlv(20, '<I', 1000)
        payload += extra
    payload = bytes((0xaa, 0x55, version, len(payload) + 6)) + payload
    return payload + crc16(payload).to_bytes(2, 'little')


class ADCProtocolTests(unittest.TestCase):
    def test_rtl_golden_and_all_fragment_boundaries(self):
        self.assertEqual(len(RTL_GOLDEN), 87)
        for split in range(1, len(RTL_GOLDEN)):
            decoder = StreamDecoder()
            self.assertEqual(decoder.feed(RTL_GOLDEN[:split]), [])
            rows = decoder.feed(RTL_GOLDEN[split:])
            self.assertEqual(len(rows), 1)
            self.assertEqual({k: rows[0][k] for k in GOLDEN_VALUES}, GOLDEN_VALUES)
            self.assertEqual(decoder.stats['crc_errors'], 0)
        decoder = StreamDecoder()
        records = []
        for byte in RTL_GOLDEN:
            records.extend(decoder.feed(bytes([byte])))
        self.assertEqual(records[0]['raw_hex'], RTL_GOLDEN.hex())

    def test_all_twenty_tlv_types_and_unknown_extension(self):
        extra = b''.join([tlv(3, '<h', 1024), tlv(4, '<h', -1024),
                          tlv(5, '<h', 512), tlv(6, '<f', .75),
                          tlv(7, '<f', -.5), tlv(8, '<I', 21), b'\xfe\x03abc'])
        row = StreamDecoder().feed(frame(extra=extra))[0]
        self.assertAlmostEqual(row['target_arm_deg'], 180 / math.pi)
        self.assertEqual(row['target_speed_rad_s'], -1)
        self.assertEqual(row['observer_confidence'], .75)
        self.assertEqual(row['energy_error'], -.5)
        self.assertEqual(row['parameter_version'], 21)
        self.assertEqual(row['adc_mean_q4'], 12265)
        self.assertEqual(row['motor_command_permille'], -200)
        self.assertEqual(row['sample_counter'], 1000)

    def test_crc_corruption_resynchronizes_to_legacy_and_v2(self):
        damaged = bytearray(RTL_GOLDEN)
        damaged[70] ^= 1
        decoder = StreamDecoder()
        rows = decoder.feed(bytes(damaged) + frame(10, version=1) + frame(11))
        self.assertEqual([r['sequence'] for r in rows], [10, 11])
        self.assertEqual(decoder.stats['crc_errors'], 1)
        self.assertNotIn('adc_raw', rows[0])
        self.assertEqual(rows[1]['firmware_version'], 0x20000)

    def test_new_tlv_wrong_size_duplicate_and_truncation_are_rejected(self):
        for kind, fmt in [(13, '<H'), (16, '<H'), (17, '<h'), (18, '<B'), (19, '<I'), (20, '<I')]:
            good = tlv(kind, fmt, 1)
            for invalid in [good + good, bytes((kind, 0)), good[:-1]]:
                with self.subTest(kind=kind, invalid=invalid):
                    decoder = StreamDecoder()
                    rows = decoder.feed(frame(1, extensions=False, extra=invalid) + frame(2))
                    self.assertEqual([r['sequence'] for r in rows], [2])
                    self.assertEqual(decoder.stats['unsupported_frames'], 1)

    def test_missing_v2_fields_are_not_synthesized_and_csv_roundtrip_keeps_values(self):
        minimal = StreamDecoder().feed(frame(extensions=False))[0]
        for key in ('adc_raw', 'adc_mean_q4', 'first_fault', 'motor_command_permille', 'firmware_version'):
            self.assertNotIn(key, minimal)
        row = StreamDecoder().feed(RTL_GOLDEN)[0]
        with tempfile.TemporaryDirectory() as tmp:
            with SessionRecorder(tmp, {'source': 'serial'}) as recorder:
                recorder.write(row)
            replay = Replay.load(recorder.directory / 'samples.csv')[0]
            self.assertEqual({k: replay[k] for k in GOLDEN_VALUES}, GOLDEN_VALUES)
            self.assertEqual(replay['source'], 'replay')

    def test_H_transport_written_signal_and_stop_supersedes_pending_capture(self):
        for stop in (False, True):
            worker = SerialWorker('TEST-NO-COM')
            self.assertTrue(worker.send('H'))
            if stop:
                self.assertTrue(worker.send('S'))
            port = FakePort(on_read=lambda: worker.request_close(False))
            written = []
            worker.command_sent.connect(written.append)
            with patch('host.transport.serial.Serial', return_value=port):
                worker.run()
            self.assertEqual(port.writes, [b'S' if stop else b'H'])
            self.assertEqual(written, ['S' if stop else 'H'])
        self.assertFalse(SerialWorker('TEST', mode='raw').send('H'))


class ADCCaptureUITests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.application = QApplication.instance() or QApplication([])

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        with patch('host.app.list_ports.comports', return_value=[]):
            self.window = Window(self.root)
        self.window.timer.stop()
        self.window.reset_data('serial')
        self.window.worker = WorkerStub()
        self.window.serial_ready = True

    def tearDown(self):
        self.window.worker = None
        self.window.close()
        self.window.deleteLater()
        self.application.processEvents()
        self.tmp.cleanup()

    def live(self, wire=None, **kwargs):
        row = StreamDecoder().feed(wire if wire is not None else frame(**kwargs))[0]
        self.window.receive([row])
        self.window.update_display()
        return row

    def check_direction(self):
        self.window.direction_check.setChecked(True)

    def events(self):
        logger = self.window.runtime_log
        self.window.close_runtime_log()
        return [json.loads(line) for line in (logger.directory / 'control.jsonl').read_text(encoding='utf-8').splitlines()]

    def test_main_panel_exposes_device_measurements_and_first_fault_without_inference(self):
        self.live(RTL_GOLDEN)
        adc = self.window.adc_diagnostic_label.text()
        for text in ('原始码 1023', '均值 510.000', '窗口 0～1023', '219 / 767',
                     '测量有效 否', '已就绪 否', '样本异常 是', '窗口 OTR 是', '实时 OTR 是', '0x00020000'):
            self.assertIn(text, adc)
        motor = self.window.motor_diagnostic_label.text()
        for text in ('请求输出 1000‰', '门控后命令 -200‰', '非引脚实测', '0x20 平衡跌落'):
            self.assertIn(text, motor)
        self.assertNotIn('速度估计停机清零', self.window.fault_label.text())
        logger = self.window.runtime_log
        self.window.close_runtime_log()
        stored = json.loads((logger.directory / 'telemetry.jsonl').read_text(encoding='utf-8').splitlines()[0])
        self.assertEqual({k: stored[k] for k in GOLDEN_VALUES}, GOLDEN_VALUES)

    def test_no_automatic_check_or_start_and_H_send_is_only_queued(self):
        self.live()
        self.assertFalse(self.window.direction_check.isChecked())
        self.assertFalse(self.window.jog_check.isChecked())
        self.assertFalse(self.window.allowed('H'))
        self.assertIn('方向', self.window.capture_gate.text())
        self.check_direction()
        self.assertTrue(self.window.allowed('H'))
        self.assertEqual(self.window.worker.sent, [])
        self.assertTrue(self.window.send_command('H'))
        self.assertEqual(self.window.worker.sent, ['H'])
        events = self.events()
        queued = [e for e in events if e['event'] == 'command_queued']
        self.assertEqual(queued[0]['command'], 'H')
        self.assertFalse(queued[0]['acknowledged'])
        gates = [e for e in events if e['event'] == 'control_availability']
        self.assertEqual([e['commands']['H']['available'] for e in gates], [False, True])
        self.assertTrue(all(not e['device_confirmed'] for e in gates))

    def test_legacy_G_still_works_H_requires_verified_new_firmware(self):
        self.check_direction()
        for kwargs in ({'version': 1}, {'firmware': None}, {'firmware': 0x10300}):
            self.live(**kwargs)
            self.assertTrue(self.window.allowed('G'))
            self.assertFalse(self.window.allowed('H'))
            self.assertIn('project-v0.2.0', self.window.command_block_reason('H'))
        self.live()
        self.assertTrue(self.window.allowed('G'))
        self.assertTrue(self.window.allowed('H'))

    def test_bad_invalid_unready_or_missing_measurement_flags_block_G_and_H(self):
        self.check_direction()
        for flags in (None, 0, 4, 8, 12 | 1, 12 | 2, 12 | 16):
            with self.subTest(flags=flags):
                self.live(flags=flags)
                for command in 'GH':
                    self.assertFalse(self.window.allowed(command))
                    self.assertIn('ADC', self.window.command_block_reason(command))
                self.assertTrue(self.window.allowed('S'))
        self.live(flags=12)
        self.assertTrue(self.window.allowed('G'))
        self.assertTrue(self.window.allowed('H'))

    def test_H_strict_q10_capture_boundaries_and_G_has_no_upright_envelope(self):
        self.check_direction()
        for theta, omega, expected in [(267, 3583, True), (-267, -3583, True),
                                       (268, 0, False), (-268, 0, False),
                                       (0, 3584, False), (0, -3584, False)]:
            with self.subTest(theta=theta, omega=omega):
                self.live(theta=theta, omega=omega)
                self.assertEqual(self.window.allowed('H'), expected)
                self.assertTrue(self.window.allowed('G'))
        self.window.latest.pop('theta_q10')
        self.window.latest.pop('omega_q10')
        self.window.latest.update(theta_deg=10.0, omega_rad_s=1.0)
        self.assertTrue(self.window.allowed('H'))
        for key, value in [('theta_deg', 15.0), ('omega_rad_s', 3.5), ('theta_deg', float('nan'))]:
            self.window.latest.update(theta_deg=0.0, omega_rad_s=0.0)
            self.window.latest[key] = value
            self.assertFalse(self.window.allowed('H'))

    def test_H_keeps_all_common_motor_gates_and_stop_priority(self):
        self.check_direction()
        for kwargs in ({'state': 2}, {'fault': 1}, {'diagnostic': 0x88}):
            self.live(**kwargs)
            self.assertFalse(self.window.send_command('H'))
            self.assertTrue(self.window.allowed('S'))
        self.live()
        self.window.latest['calibrated'] = 0
        self.assertFalse(self.window.allowed('H'))
        self.window.latest['calibrated'] = 1
        self.window.last_received = time.monotonic() - 2
        self.assertFalse(self.window.allowed('H'))
        self.assertTrue(self.window.allowed('S'))
        self.assertEqual(self.window.worker.sent, [])

    def test_F_B_existing_clearance_gate_is_unchanged(self):
        self.live(flags=0)
        self.assertFalse(self.window.allowed('F'))
        self.window.jog_check.setChecked(True)
        self.assertTrue(self.window.allowed('F'))
        self.assertTrue(self.window.allowed('B'))
        self.assertFalse(self.window.allowed('G'))
        self.assertFalse(self.window.allowed('H'))

    def test_old_frame_never_reuses_prior_adc_or_first_fault_and_stale_is_explicit(self):
        self.live(RTL_GOLDEN)
        self.window.last_received = time.monotonic() - 2
        self.window.update_display()
        self.assertIn('已超时', self.window.adc_diagnostic_label.text())
        self.assertIn('已超时', self.window.motor_diagnostic_label.text())
        self.live(version=1, fault=0x21)
        self.assertIn('未提供', self.window.adc_diagnostic_label.text())
        self.assertIn('首次故障：未提供', self.window.motor_diagnostic_label.text())
        self.assertNotIn('0x20', self.window.motor_diagnostic_label.text())

    def test_replay_and_demo_never_send_H_even_with_new_firmware_fields(self):
        self.live()
        self.check_direction()
        for source in ('replay', 'demo'):
            self.window.source = source
            self.assertFalse(self.window.send_command('H'))
        self.assertEqual(self.window.worker.sent, [])

    def test_fixed_stop_remains_visible_in_small_window_with_ADC_diagnostics(self):
        from PySide6.QtCore import QPoint
        self.live()
        self.window.resize(1000, 750)
        self.window.show()
        self.application.processEvents()
        stop = self.window.global_stop
        top_left = stop.mapTo(self.window, QPoint(0, 0))
        bottom_right = stop.mapTo(self.window, stop.rect().bottomRight())
        self.assertEqual(self.window.size().width(), 1000)
        self.assertTrue(self.window.rect().contains(top_left))
        self.assertTrue(self.window.rect().contains(bottom_right))
        self.assertLess(bottom_right.y(), 100)
        self.assertTrue(stop.isVisible())
        self.assertTrue(stop.isEnabled())


if __name__ == '__main__':
    unittest.main()
